services:
  flask:
    container_name: sqli_flask
    hostname: flask
    build: ./flask_app
    ports:
      - "8000:5000"
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: vulnapp
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
    depends_on:
      - mariadb
    networks:
      - lab-network

  php_apache:
    container_name: sqli_php_apache
    hostname: php_apache
    build: ./php_app
    ports:
      - "8010:80"
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: vulnapp
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
    depends_on:
      - mariadb
    networks:
      - lab-network

  mariadb:
    container_name: sqli_mariadb
    image: mariadb:11.8.1-ubi9-rc
    hostname: mariadb
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      MARIADB_ROOT_PASSWORD: toor
    restart: always
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge


