services:
  flask:
    container_name: flask
    hostname: flask
    build: ./app
    ports:
      - "8000:5000"
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT=${MARIADB_PORT}
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:11.8.1-ubi9-rc
    hostname: mariadb
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: always



