version: "3"

services:
  flask:
    container_name: flask
    hostname: flask
    build: ./app
    ports:
      - "8000:5000"
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: vulnapp
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:11.8.1-ubi9-rc
    hostname: mariadb
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: always



